<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { addBillLine, getBill, voidBill } from '@/api/trade'
import { getEmployees, getServices } from '@/api/masterData'
import { useAuthStore } from '@/stores/auth'
import type { BillDetail, EmployeeSummary, ServiceItemSummary } from '@/types/api'
import { formatMoney } from '@/utils/formatMoney'

const route = useRoute(); const router = useRouter(); const auth = useAuthStore(); const billId = Number(route.params.billId)
const loading = ref(true); const saving = ref(false); const addVisible = ref(false); const voidVisible = ref(false)
const detail = ref<BillDetail | null>(null); const services = ref<ServiceItemSummary[]>([]); const employees = ref<EmployeeSummary[]>([])
const lineForm = reactive({ serviceId: undefined as number | undefined, quantity: 1, employeeId: undefined as number | undefined, note: '' })
const voidForm = reactive({ reasonCode: 'CUSTOMER_CHANGE', note: '' })

async function load() { loading.value = true; try { detail.value = await getBill(billId) } catch (error) { ElMessage.error(error instanceof Error ? error.message : '账单加载失败') } finally { loading.value = false } }
async function openAdd() { if (!detail.value) return; [services.value, employees.value] = await Promise.all([getServices({ storeId: detail.value.bill.storeId }), getEmployees({ storeId: detail.value.bill.storeId })]); Object.assign(lineForm, { serviceId: undefined, quantity: 1, employeeId: undefined, note: '' }); addVisible.value = true }
async function submitLine() { if (!detail.value || !lineForm.serviceId) { ElMessage.warning('请选择服务项目'); return } saving.value = true; try { detail.value = await addBillLine(billId, { serviceId: lineForm.serviceId, quantity: lineForm.quantity, employeeId: lineForm.employeeId, note: lineForm.note || undefined, version: detail.value.bill.version }); addVisible.value = false; ElMessage.success('消费项目已添加') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '添加失败') } finally { saving.value = false } }
async function submitVoid() { if (!detail.value) return; saving.value = true; try { detail.value = await voidBill(billId, { reasonCode: voidForm.reasonCode, note: voidForm.note || undefined, version: detail.value.bill.version }); voidVisible.value = false; ElMessage.success('账单已作废') } catch (error) { ElMessage.error(error instanceof Error ? error.message : '作废失败') } finally { saving.value = false } }
function dateTime(value?: string) { return value?.replace('T', ' ').slice(0, 19) ?? '—' }
onMounted(load)
</script>

<template>
  <section v-loading="loading" class="page-content"><template v-if="detail"><div class="section-title-row"><div class="member-title-block"><el-button link @click="router.push('/app/bills')">← 返回账单列表</el-button><div class="member-title-line"><h1>{{ detail.bill.billNo }}</h1><el-tag>{{ detail.bill.status }}</el-tag></div><p>{{ detail.bill.customerName }} · {{ detail.bill.storeName }} · {{ dateTime(detail.bill.createdAt) }}</p></div><div><el-button v-if="['DRAFT','PENDING_PAYMENT'].includes(detail.bill.status) && auth.hasPermission('trade:bill:manage')" @click="voidVisible = true">作废</el-button><el-button v-if="['DRAFT','PENDING_PAYMENT'].includes(detail.bill.status) && auth.hasPermission('trade:bill:manage')" @click="openAdd">添加项目</el-button><el-button v-if="detail.lines.length && ['DRAFT','PENDING_PAYMENT'].includes(detail.bill.status) && auth.hasPermission('trade:bill:settle')" type="primary" @click="router.push(`/app/bills/${billId}/settle`)">收银结算</el-button></div></div><div class="bill-amount-grid"><article><span>原价</span><strong>{{ formatMoney(detail.bill.originalAmount) }}</strong></article><article><span>优惠</span><strong>{{ formatMoney(detail.bill.discountAmount) }}</strong></article><article class="accent"><span>应收</span><strong>{{ formatMoney(detail.bill.receivableAmount) }}</strong></article><article><span>实收</span><strong>{{ formatMoney(detail.bill.receivedAmount) }}</strong></article></div><el-card class="data-card" shadow="never"><template #header><strong>消费明细</strong></template><el-table :data="detail.lines"><el-table-column prop="lineNo" label="#" width="60" /><el-table-column prop="itemName" label="项目" min-width="220" /><el-table-column prop="employeeName" label="服务技师" width="140" /><el-table-column prop="quantity" label="数量" width="90" /><el-table-column label="单价" width="120" align="right"><template #default="scope">{{ formatMoney(scope.row.unitPrice) }}</template></el-table-column><el-table-column label="应收" width="130" align="right"><template #default="scope">{{ formatMoney(scope.row.receivableAmount) }}</template></el-table-column></el-table></el-card><el-card v-if="detail.payments.length" class="data-card bill-secondary-card" shadow="never"><template #header><strong>支付明细</strong></template><el-table :data="detail.payments"><el-table-column prop="paymentMethodName" label="方式" /><el-table-column prop="externalReference" label="凭证号" /><el-table-column label="金额" align="right"><template #default="scope">{{ formatMoney(scope.row.amount) }}</template></el-table-column><el-table-column prop="paidAt" label="支付时间" /></el-table></el-card></template>
    <el-dialog v-model="addVisible" title="添加消费项目" width="620px"><el-form label-width="90px"><el-form-item label="服务项目" required><el-select v-model="lineForm.serviceId" class="dialog-full-control"><el-option v-for="item in services" :key="item.id" :label="`${item.name} · ${formatMoney(item.storePrice)}`" :value="item.id" /></el-select></el-form-item><el-form-item label="数量"><el-input-number v-model="lineForm.quantity" :min="0.0001" :precision="2" /></el-form-item><el-form-item label="服务技师"><el-select v-model="lineForm.employeeId" clearable class="dialog-full-control"><el-option v-for="item in employees.filter((employee) => employee.canService)" :key="item.id" :label="item.name" :value="item.id" /></el-select></el-form-item><el-form-item label="备注"><el-input v-model="lineForm.note" /></el-form-item></el-form><template #footer><el-button @click="addVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="submitLine">添加</el-button></template></el-dialog>
    <el-dialog v-model="voidVisible" title="作废账单" width="500px"><el-form label-width="90px"><el-form-item label="原因"><el-select v-model="voidForm.reasonCode"><el-option label="客户取消消费" value="CUSTOMER_CHANGE" /><el-option label="开单错误" value="BILL_ERROR" /><el-option label="其他" value="OTHER" /></el-select></el-form-item><el-form-item label="说明"><el-input v-model="voidForm.note" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="voidVisible = false">取消</el-button><el-button type="danger" :loading="saving" @click="submitVoid">确认作废</el-button></template></el-dialog>
  </section>
</template>
